apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::655765846357:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-FB7X285TWM7U
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-18T18:53:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "862"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bf5cea81-6949-11ea-89bd-062bd8a3aa50

